/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package study_buddy;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.ResultSet;

/**
 *
 * @author invincible
 */
public class User_Register extends javax.swing.JFrame {

    /**
     * Creates new form User_Register
     */
    public User_Register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        ut1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ut2 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ut3 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ut4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("WELCOME BRO ,");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 570, 60));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 0));
        jLabel2.setText("search down here what you need");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 60, 440, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 1330, 100));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setText(" COURSE :");
        jLabel3.setOpaque(true);
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 230, 40));

        ut1.setForeground(new java.awt.Color(255, 102, 0));
        ut1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "B.Tech", "M.Tech", "BCA", "MCA" }));
        ut1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 5, 10)));
        ut1.setOpaque(true);
        jPanel2.add(ut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, 290, 40));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 102, 0));
        jLabel4.setText(" YEAR :");
        jLabel4.setOpaque(true);
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 230, 40));

        ut2.setForeground(new java.awt.Color(255, 102, 0));
        ut2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023" }));
        ut2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 5, 10)));
        ut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut2ActionPerformed(evt);
            }
        });
        jPanel2.add(ut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 290, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Nirmala UI", 1, 20)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 102, 0));
        jLabel5.setText(" SUBJECT CODE :");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 230, 40));

        ut3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOTES", "EXE", "PDF", " " }));
        ut3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 5, 10)));
        ut3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ut3ActionPerformed(evt);
            }
        });
        jPanel2.add(ut3, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 290, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 102, 0));
        jLabel6.setText(" FILE TYPE :");
        jLabel6.setOpaque(true);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 230, 40));

        ut4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 5, 10)));
        jPanel2.add(ut4, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 290, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Nirmala UI", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 0));
        jButton1.setText("SEARCH");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 490, 240, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 1330, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut2ActionPerformed

    private void ut3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ut3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ut3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
             {                                    

     
              String cr1=ut1.getSelectedItem().toString();
              String yr1=ut2.getSelectedItem().toString();
              String tp1=ut3.getSelectedItem().toString();
             // String flnm1=ut5.getText();
              String sbcd1=ut4.getText();
              admin_registerdata s3=new admin_registerdata();

          /*  String sql = "select * from data where Course = '"+cr1+"' AND Year = '"+yr1+"' AND Type = '"+tp1+"' AND FileName = '"+flnm1+"' AND Subject_Code = '"+sbcd1+"';";
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/world", "root", "root");
//            System.out.println(sql);

            Statement stmt = conn.createStatement();
            ResultSet  rs = stmt.executeQuery(sql);
            System.out.println(rs);*/
          try{
          String sql = "select * from data where Course = '"+cr1+"' AND Year = '"+yr1+"' AND Type = '"+tp1+"' AND Sub_Code = '"+sbcd1+"';";
          Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/studybuddy", "root", "tyagi@2314Aryan");
          Statement stmt = conn.createStatement();
          ResultSet  rs = stmt.executeQuery(sql);
          System.out.println(rs);
            int count  = 0 ;
            while(rs.next())
            {
                 System.out.println("heloo 121");
                count++;
                System.out.println("Data Found Successfully");
                System.out.println(rs.getString("Course"));
                System.out.println(rs.getString("Year"));
                System.out.println(rs.getString("Type"));
            //   System.out.println(rs.getString("Filename"));
              //System.out.println(rs.getString("Subject_Code"));

              String url = rs.getString("file_name");
              
               // s3.setFile(flnm1);
                this.setVisible(false);
                new FILE_FOUND(url,tp1).setVisible(true);
                
            } 
            
            if(count == 0 ){
             // JOptionPane.showMessageDialog(this, "Data Not Found In The DataBase");
                 this.setVisible(false);
                new filenotfound().setVisible(true);
                

            }
        }
          catch(Exception e){
            e.printStackTrace();
            System.out.println("Due to Some Error Data not Show Properly.....");
    }

    }
             
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> ut1;
    private javax.swing.JComboBox<String> ut2;
    private javax.swing.JComboBox<String> ut3;
    private javax.swing.JTextField ut4;
    // End of variables declaration//GEN-END:variables
}
